//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauThietKePhanMem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;


    public interface MatHangPrototype
    {
        MatHangPrototype Clone();
    }

    public partial class MatHang : MatHangPrototype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatHang()
        {
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
        }
    
        public int IDMH { get; set; }
        public string TenMH { get; set; }
        public Nullable<int> IDLoaiMH { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<System.DateTime> NgayNhapHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public byte[] HinhAnh1 { get; set; }
        public byte[] HinhAnh2 { get; set; }
        public byte[] HinhAnh3 { get; set; }
        public byte[] HinhAnh4 { get; set; }
        public string MoTaChiTiet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        public virtual LoaiMatHang LoaiMatHang { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage1 { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage2 { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage3 { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage4 { get; set; }


        public MatHangPrototype Clone()
        {
            MatHang mh = new MatHang();
            mh.TenMH = TenMH;
            mh.IDLoaiMH = IDLoaiMH;
            mh.MoTa = MoTa;
            mh.DonGia = DonGia;
            mh.MoTaChiTiet = MoTaChiTiet;
            mh.NgayNhapHang = NgayNhapHang;
            mh.SoLuong = SoLuong;
            mh.HinhAnh1 = HinhAnh1;
            mh.HinhAnh4 = HinhAnh4;
            mh.HinhAnh3 = HinhAnh3;
            mh.HinhAnh2 = HinhAnh2;

            return mh;
        }
    }
}
